### ISSUE TITLE
Download fails with: Response status code does not indicate success: 400 (Bad Request).

### ISSUE THREAD

**Issue by tjgordon** [redbaty/Wasari#5]
Attempting to download episode 1 of https://beta.crunchyroll.com/series/G4PH0WXVJ fails with the following output.

```
PS C:\Users\tgord\crunchyroll> D:\Users\tgord\Apps\Wasari.exe crunchy https://beta.crunchyroll.com/series/G4PH0WXVJ -e 1
[21:39:55 INF] Logging to file at path C:\Users\tgord\AppData\Roaming\Wasari\logs\log.txt
[21:39:58 INF] Available environment features: ["YtDlp", "Ffmpeg", "NvidiaGpu"]
[21:39:58 INF] Current version is: 1.0.62.0
[21:39:58 INF] BETA Series detected
[21:39:58 INF] Start processing HTTP request POST https://beta-api.crunchyroll.com/auth/v1/token
[21:39:58 INF] Sending HTTP request POST https://beta-api.crunchyroll.com/auth/v1/token
[21:39:58 INF] Received HTTP response headers after 237.5106ms - 200
[21:39:58 INF] End processing HTTP request after 247.9265ms - 200
[21:39:58 INF] Created unauthenticated API service
[21:39:58 INF] NVIDIA hardware acceleration is available
ERROR
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
  at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
  at JsonExtensions.Http.HttpExtensions.GetJsonAsync(HttpClient httpClient, Uri requestUri, CancellationToken cancellationToken) in \_\JsonExtensions\Http\HttpExtensions.cs:41
  at JsonExtensions.Http.HttpExtensions.GetJsonAsync(HttpClient httpClient, String requestUri, CancellationToken
 cancellationToken) in \_\JsonExtensions\Http\HttpExtensions.cs:53
  at Wasari.Crunchyroll.API.CrunchyrollApiService.GetSeasons(String seriesId)+MoveNext()
  at Wasari.Crunchyroll.API.CrunchyrollApiService.GetSeasons(String seriesId)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
  at System.Collections.Generic.AsyncEnumerableHelpers.ToArrayWithLength[T](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in \_\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncEnumerableHelpers.cs:49
  at System.Collections.Generic.AsyncEnumerableHelpers.ToArrayWithLength[T](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in \_\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncEnumerableHelpers.cs:91
  at System.Collections.Generic.AsyncEnumerableHelpers.ToArray[T](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in \_\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncEnumerableHelpers.cs:16
  at Wasari.Crunchyroll.BetaCrunchyrollService.GetEpisodes(String url)+MoveNext()
  at Wasari.Crunchyroll.BetaCrunchyrollService.GetEpisodes(String url)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
  at System.Linq.AsyncEnumerable.WhereEnumerableAsyncIterator`1.MoveNextCore() in \_\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\Where.cs:233
  at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in \_\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncIterator.cs:70
  at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in \_\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncIterator.cs:75
  at System.Collections.Generic.AsyncEnumerableHelpers.ToArrayWithLength[T](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in \_\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncEnumerableHelpers.cs:49
  at System.Collections.Generic.AsyncEnumerableHelpers.ToArrayWithLength[T](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in \_\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncEnumerableHelpers.cs:91
  at System.Linq.OrderedAsyncEnumerable`1.ToArrayAsync(CancellationToken cancellationToken) in \_\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\OrderedAsyncEnumerable.cs:84
  at System.Linq.OrderedAsyncEnumerable`1.MoveNextCore() in \_\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\OrderedAsyncEnumerable.cs:47
  at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in \_\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncIterator.cs:70
  at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in \_\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncIterator.cs:75
  at System.Linq.Internal.Lookup`2.CreateAsync(IAsyncEnumerable`1 source, Func`2 keySelector, IEqualityComparer`kup.cs:105
  at System.Linq.Internal.Lookup`2.CreateAsync(IAsyncEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer, CancellationToken cancellationToken) in \_\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\Lookup.cs:105
  at System.Linq.AsyncEnumerable.GroupedAsyncEnumerable`2.MoveNextCore() in \_\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\GroupBy.cs:1094
  at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in \_\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncIterator.cs:70
  at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in \_\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncIterator.cs:75
  at Wasari.App.EpisodeExtensions.GetEpisodesGrouped(IAsyncEnumerable`1 episodes)+MoveNext()
  at Wasari.App.EpisodeExtensions.GetEpisodesGrouped(IAsyncEnumerable`1 episodes)+MoveNext()
  at Wasari.App.EpisodeExtensions.GetEpisodesGrouped(IAsyncEnumerable`1 episodes)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
  at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in \_\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\ToList.cs:36
  at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in \_\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\ToList.cs:36
  at Wasari.App.DownloadSeriesService.DownloadEpisodes(Uri url, DownloadParameters downloadParameters)
  at Wasari.Commands.CrunchyrollDownloadSeriesCommand.ExecuteAsync(IConsole console)
  at CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in D:\a\CliFx\CliFx\CliFx\CliApplication.cs:147
  at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables) in D:\a\CliFx\CliFx\CliFx\CliApplication.cs:191
```

Trying episode 1 of https://beta.crunchyroll.com/series/GRJ0J828Y/kaguya-sama-love-is-war also fails, but with a different error, " The method or operation is not implemented":

```
PS C:\Users\tgord\crunchyroll> D:\Users\tgord\Apps\Wasari.exe crunchy https://beta.crunchyroll.com/series/GRJ0J828Y/kaguya-sama-love-is-war -e 1
[21:50:16 INF] Logging to file at path C:\Users\tgord\AppData\Roaming\Wasari\logs\log.txt
[21:50:18 INF] Available environment features: ["YtDlp", "Ffmpeg", "NvidiaGpu"]
[21:50:18 INF] Current version is: 1.0.62.0
[21:50:18 INF] BETA Series detected
[21:50:18 INF] Start processing HTTP request POST https://beta-api.crunchyroll.com/auth/v1/token
[21:50:18 INF] Sending HTTP request POST https://beta-api.crunchyroll.com/auth/v1/token
[21:50:18 INF] Received HTTP response headers after 244.5916ms - 200
[21:50:18 INF] End processing HTTP request after 255.2684ms - 200
[21:50:18 INF] Created unauthenticated API service
[21:50:18 INF] NVIDIA hardware acceleration is available
ERROR
System.NotImplementedException: The method or operation is not implemented.
  at Wasari.Crunchyroll.API.Converters.ThumbnailsConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
  at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
  at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
  at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
  at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
  at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
  at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
  at System.Text.Json.JsonSerializer.ReadUsingMetadata[TValue](JsonElement element, JsonTypeInfo jsonTypeInfo)
  at System.Text.Json.JsonSerializer.Deserialize[TValue](JsonElement element, JsonSerializerOptions options)
  at Wasari.Crunchyroll.API.CrunchyrollApiService.GetEpisodes(String seasonId)+MoveNext()
  at Wasari.Crunchyroll.API.CrunchyrollApiService.GetEpisodes(String seasonId)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
  at System.Collections.Generic.AsyncEnumerableHelpers.ToArrayWithLength[T](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in \_\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncEnumerableHelpers.cs:49
  at System.Collections.Generic.AsyncEnumerableHelpers.ToArrayWithLength[T](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in \_\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncEnumerableHelpers.cs:91
  at System.Collections.Generic.AsyncEnumerableHelpers.ToArray[T](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in \_\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncEnumerableHelpers.cs:16
  at TomLonghurst.EnumerableAsyncProcessor.RunnableProcessors.ResultProcessors.Abstract.ResultAbstractAsyncProcessor`2.ProcessItem(Tuple`2 itemTaskCompletionSourceTuple)
  at Wasari.Crunchyroll.BetaCrunchyrollService.GetEpisodes(String url)+MoveNext()
  at Wasari.Crunchyroll.BetaCrunchyrollService.GetEpisodes(String url)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
  at System.Linq.AsyncEnumerable.WhereEnumerableAsyncIterator`1.MoveNextCore() in \_\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\Where.cs:233
  at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in \_\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncIterator.cs:70
  at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in \_\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncIterator.cs:75
  at System.Collections.Generic.AsyncEnumerableHelpers.ToArrayWithLength[T](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in \_\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncEnumerableHelpers.cs:49
  at System.Collections.Generic.AsyncEnumerableHelpers.ToArrayWithLength[T](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in \_\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncEnumerableHelpers.cs:91
  at System.Linq.OrderedAsyncEnumerable`1.ToArrayAsync(CancellationToken cancellationToken) in \_\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\OrderedAsyncEnumerable.cs:84
  at System.Linq.OrderedAsyncEnumerable`1.MoveNextCore() in \_\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\OrderedAsyncEnumerable.cs:47
  at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in \_\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncIterator.cs:70
  at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in \_\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncIterator.cs:75
  at System.Linq.Internal.Lookup`2.CreateAsync(IAsyncEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer, CancellationToken cancellationToken) in \_\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\Lookup.cs:105
  at System.Linq.Internal.Lookup`2.CreateAsync(IAsyncEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer, CancellationToken cancellationToken) in \_\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\Lookup.cs:105
  at System.Linq.AsyncEnumerable.GroupedAsyncEnumerable`2.MoveNextCore() in \_\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\GroupBy.cs:1094
  at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in \_\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncIterator.cs:70
  at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in \_\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncIterator.cs:75
  at Wasari.App.EpisodeExtensions.GetEpisodesGrouped(IAsyncEnumerable`1 episodes)+MoveNext()
  at Wasari.App.EpisodeExtensions.GetEpisodesGrouped(IAsyncEnumerable`1 episodes)+MoveNext()
  at Wasari.App.EpisodeExtensions.GetEpisodesGrouped(IAsyncEnumerable`1 episodes)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
  at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in \_\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\ToList.cs:36
  at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in \_\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\ToList.cs:36
  at Wasari.App.DownloadSeriesService.DownloadEpisodes(Uri url, DownloadParameters downloadParameters)
  at Wasari.Commands.CrunchyrollDownloadSeriesCommand.ExecuteAsync(IConsole console)
  at CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in D:\a\CliFx\CliFx\CliFx\CliApplication.cs:147
  at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables) in D:\a\CliFx\CliFx\CliFx\CliApplication.cs:191
```

I also tried passing the username and password as command line options rather than using the environment variables, but got the same result.

### Environment
Wasari 1.0.62.0
Windows 10
```
PS C:\Users\tgord\crunchyroll> $PSVersionTable. PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1682
```
My account is a "Fan" level premium account.

**Comment by tjgordon** [comment]
Log file is not included due to https://github.com/redbaty/Wasari/issues/6 .

**Comment by mvmcjr** [comment]
Hey @tjgordon, thanks for the report! It turns out my regex is expecting a slash at the end of the URL, and this episode is currently premium only so as a workaround you could just call it like this:

`crunchy https://beta.crunchyroll.com/series/G4PH0WXVJ/ -e 1 -u <crunchyroll-username> -p <crunchyroll-password>` With the `/` at the end of the URL.

**Comment by tjgordon** [comment]
Thanks. It worked after adding a trailing slash on 1.0.62.0, and also without a trailing slash on https://github.com/redbaty/Wasari/releases/tag/63 and https://github.com/redbaty/Wasari/releases/tag/65.
